spring:
  profiles:
    active: live
  batch:
    job:
      names: ${job.name:NONE}

logging.level.org.springframework.batch: DEBUG

--- # local
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver

--- # dev
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver

--- # live server
spring:
  profiles: live

db:
  batch:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://39.118.30.247:7901/BATCH
    username: root
    password: root
  service:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://39.118.30.247:7901/BATCH_SERVICE
    username: root
    password: root